branch-defaults:
  main:
    environment: zmylong-env
environment:
  name: zmylong-env
  platform: Java 17 running on 64bit Amazon Corretto
  tier: WebServer
global:
  application_name: zmylong-productivity
  default_region: ap-northeast-2
  profile: null
  workspace_type: Application
