import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import NotFoundPage from '@/features/layout/pages/NotFoundPage';
import LoginPage from '@/features/auth/pages/LoginPage';
import UserHomePage from '@/features/user/pages/UserHomePage';
import PrivateRoute from './PrivateRoute';
import DiaryInputPage from '@/features/diary/pages/DiaryInputPage';
import CalendarPage from '@/features/calendar/pages/CalendarPage';
import DiaryListPage from '@/features/diary/pages/DiaryListPage';
import DiaryInsightsPage from '@/features/statistics/pages/EmotionStatsPage';
import SearchResultPage from '@/features/search/pages/SearchResultPage';
const AppRouter = () => (_jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/", element: _jsx(PrivateRoute, { children: _jsx(Navigate, { to: "/user/home", replace: true }) }) }), _jsx(Route, { path: "/user/home", element: _jsx(PrivateRoute, { children: _jsx(UserHomePage, {}) }) }), " ", _jsx(Route, { path: "/user/diary-form", element: _jsx(PrivateRoute, { children: _jsx(DiaryInputPage, {}) }) }), " ", _jsx(Route, { path: "/user/calendar", element: _jsx(PrivateRoute, { children: _jsx(CalendarPage, {}) }) }), _jsx(Route, { path: "/user/diary-list", element: _jsx(PrivateRoute, { children: _jsx(DiaryListPage, {}) }) }), _jsx(Route, { path: "/user/diary-insights", element: _jsx(PrivateRoute, { children: _jsx(DiaryInsightsPage, {}) }) }), _jsx(Route, { path: "/user/search-result", element: _jsx(PrivateRoute, { children: _jsx(SearchResultPage, {}) }) }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] }));
export default AppRouter;
