# backend/src/main/resources/application-sample.yml

spring:
  datasource:
    url: jdbc:mysql://your-db-host:3306/your-db-name
    username: your-db-username
    password: your-db-password

jwt:
  secret: your-jwt-secret-key

openai:
  api:
    key: your-openai-api-key
